tabix_path: "tabix"

# Note that this should be the "newer" PLINK.
# See: https://www.cog-genomics.org/plink2
plink_path: "plink"

gwas_catalogs:
  hg19:
    ebi: "data/gwascat/gwascat_ebi_GRCh37p13.tab"

ld_sources:
  hg19:
    1000G_2012-03_EUR: "data/ld/trim_phase1_release_v3.20101123.snps.genotypes.EUR.vcf.gz"
    1000G_2012-03_AFR: "data/ld/trim_phase1_release_v3.20101123.snps.genotypes.AFR.vcf.gz"
    1000G_2012-03_AMR: "data/ld/trim_phase1_release_v3.20101123.snps.genotypes.AMR.vcf.gz"
    1000G_2012-03_ASN: "data/ld/trim_phase1_release_v3.20101123.snps.genotypes.ASN.vcf.gz"

